export const RAW_PREVIEW_TARGET_LONGEST_EDGE = 1600;
export const RAW_PREVIEW_ACCEPTANCE_STEPS = [
  RAW_PREVIEW_TARGET_LONGEST_EDGE,
  1024,
  512,
  1,
] as const;
export const RAW_PREVIEW_MAX_EMBEDDED_JPEG_CANDIDATES = 24;
